name: Python package

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10", "3.11", "3.12"]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Set up pip cache
              if: runner.os == 'Linux'
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
                  restore-keys: ${{ runner.os }}-pip-
            - name: Install Hatch
              run: pipx install hatch
            - name: Run lint
              run: hatch run lint:all
            - name: Run tests
              run: hatch run cov
            - name: Build dist
              run: hatch build
